[package]
name = "threadrunner-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
serde_json = "1"
tokio = { workspace = true, features = ["net", "time", "signal"] }
threadrunner-core = { path = "../core", features = [] }

[dev-dependencies]
tempfile = "3" 