[package]
name = "threadrunner-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
tokio.workspace = true
thiserror.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1" 