name: CI

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: TODO
        run: echo "Add format job steps"
    
  check:
    runs-on: ubuntu-latest
    steps:
      - name: TODO
        run: echo "Add check job steps" 