name: CI

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: TODO
        run: echo "Add format job steps"
    
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Check code
        run: cargo check --workspace
      - name: Run tests
        env:
          RUSTFLAGS: "-D warnings"
        run: cargo test --workspace

  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Test dummy backend (default)
          - name: "Dummy Backend"
            features: ""
            check_cmd: "cargo check --workspace"
            test_cmd: "cargo test --workspace"
          # Test llama backend 
          - name: "Llama Backend"
            features: "core/llama"
            check_cmd: "cargo check --workspace --no-default-features --features \"core/llama\""
            test_cmd: "cargo test --workspace --no-default-features --features \"core/llama\""
    name: Build (${{ matrix.name }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Check compilation - ${{ matrix.name }}
        run: ${{ matrix.check_cmd }}
      - name: Run tests - ${{ matrix.name }}
        env:
          RUSTFLAGS: "-D warnings"
        run: ${{ matrix.test_cmd }}

  lint-formula:
    name: Lint Homebrew Formula
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "$(/opt/homebrew/bin/brew shellenv)" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Update Homebrew
        run: brew update

      - name: Audit formula
        run: brew audit --formula Formula/threadrunner.rb --strict --online

      - name: Check formula style
        run: brew style Formula/threadrunner.rb 